// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3cUchOh57252A0WRhkxTcOgpDlmaeebs',
    appId: '1:1083439063495:web:c30492384026f24733b9e2',
    messagingSenderId: '1083439063495',
    projectId: 'spacenews-core-natan',
    authDomain: 'spacenews-core-natan.firebaseapp.com',
    storageBucket: 'spacenews-core-natan.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdoqRjGfcVxYxvPEh7GIBaTH3ntsAupqA',
    appId: '1:1083439063495:android:ce45dd785f9f0cab33b9e2',
    messagingSenderId: '1083439063495',
    projectId: 'spacenews-core-natan',
    storageBucket: 'spacenews-core-natan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqfQgxcGvEOnS_cdYsRPx2eEDS6QTkpVs',
    appId: '1:1083439063495:ios:ecd8becb963c20aa33b9e2',
    messagingSenderId: '1083439063495',
    projectId: 'spacenews-core-natan',
    storageBucket: 'spacenews-core-natan.firebasestorage.app',
    iosBundleId: 'com.example.remidi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqfQgxcGvEOnS_cdYsRPx2eEDS6QTkpVs',
    appId: '1:1083439063495:ios:ecd8becb963c20aa33b9e2',
    messagingSenderId: '1083439063495',
    projectId: 'spacenews-core-natan',
    storageBucket: 'spacenews-core-natan.firebasestorage.app',
    iosBundleId: 'com.example.remidi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3cUchOh57252A0WRhkxTcOgpDlmaeebs',
    appId: '1:1083439063495:web:77db1e19cb2348da33b9e2',
    messagingSenderId: '1083439063495',
    projectId: 'spacenews-core-natan',
    authDomain: 'spacenews-core-natan.firebaseapp.com',
    storageBucket: 'spacenews-core-natan.firebasestorage.app',
  );
}
